title: Microclimate
email: tiaoyuw@ca.ibm.com
description: IBM Microclimate
baseurl: ""
url: ""
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

include: ['docPages']
